on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:

  # Compila o código
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32
        path: ''
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: output_binaries
        path: build/espnow_example.bin
