on:
  workflow_dispatch:

  push:
    branches:
      - master

jobs:

  # Compila o código
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        path: $GITHUB_WORKSPACE/project
        
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.1
        target: esp32
        path: '$GITHUB_WORKSPACE/project'
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: output_binaries
        path: $GITHUB_WORKSPACE/project/build/*.bin
        if-no-files-found: error
