on:
  workflow_dispatch:

  push:
    branches:
      - main
      - pull_request

jobs:

  # Compila o código
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        path: project
        
    - name: esp-idf build
      uses: espressif/esp-idf-ci-action@v1
      with:
        esp_idf_version: v5.3
        target: esp32s3
        path: './project'
        
    - name: Archive code coverage results
      uses: actions/upload-artifact@v4
      with:
        name: output_binaries
        path: './project/build/*.bin'
        if-no-files-found: error
